# Generated by Django 4.1.7 on 2023-04-12 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_tag_alter_product_description_product_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_id',
        ),
    ]
